module.exports = function(grunt) {

  var config = {
    clean: {
      public: 'public/**/*'
    },
    jade: {
      demo: {
        files: [{
          expand: true,
          cwd: 'demo/',
          src: '*.jade',
          dest: 'public/',
          ext: '.html'
        }],
        options: {
          pretty: true,
          data: {
            bower: require('./bower.json'),
            pkg: require('./package.json')
          }
        }
      }
    },
    stylus: {
      src: {
        files: [{
          expand: true,
          cwd: 'src/',
          src: '*.styl',
          dest: 'dist/',
          ext: '.css'
        }],
        options: {
          compress: false
        }
      },
      demo: {
        files: [{
          expand: true,
          cwd: 'demo/styles/',
          src: '**/*.styl',
          dest: 'public/styles/',
          ext: '.css'
        }],
        options: {
          compress: false
        }
      }
    },
    copy: {
      dist: {
        files: [{
          expand: true,
          cwd: 'dist/',
          src: '**/*',
          dest: 'public/dist/'
        }]
      },
      demo: {
        files: [{
          expand: true,
          cwd: 'demo/',
          src: [
            '**/*',
            '../dist',
            '!<%= jade.demo.files[0].src %>',
            '!<%= stylus.demo.files[0].src %>'
          ],
          dest: 'public/'
        }]
      }
    },
    watch: {
      jade: {
        files: ['demo/bower_components/bespoke-themeboilerplate/mixin.jade', '<%= jade.demo.files[0].cwd + jade.demo.files[0].src %>'],
        tasks: 'jade'
      },
      stylus: {
        files: [
          '<%= stylus.src.files[0].cwd + stylus.src.files[0].src %>',
          '<%= stylus.demo.files[0].cwd + stylus.demo.files[0].src %>'
        ],
        tasks: 'stylus'
      },
      copy: {
        files: [
          '<%= copy.dist.files[0].cwd + copy.dist.files[0].src[0] %>',
          '<%= copy.demo.files[0].cwd + copy.demo.files[0].src[0] %>',
          '!<%= jade.demo.files[0].cwd + jade.demo.files[0].src %>',
          '!<%= stylus.src.files[0].cwd + stylus.src.files[0].src %>',
          '!<%= stylus.demo.files[0].cwd + stylus.demo.files[0].src %>'
        ],
        tasks: 'copy'
      },
      public: {
        files: [
          'public/**/*',
          '!public/bower_components/**/*'
        ],
        options: {
          livereload: 35729
        }
      }
    },
    connect: {
      server: {
        options: {
          port: 8000,
          hostname: '*', // Remove this line if you only want the server available locally
          base: 'public',
          keepalive: true,
          middleware: function(connect, options) {
            return [
              require('connect-livereload')({
                port: config.watch.public.options.livereload
              }),
              connect.static(options.base)
            ];
          }
        }
      }
    },
    open: {
      server: {
        path: 'http://localhost:<%= connect.server.options.port %>'
      }
    },
    concurrent: {
      compile: {
        tasks: [
          'jade',
          'stylus'
        ],
        options: {
          logConcurrentOutput: false
        }
      },
      server: {
        tasks: [
          'connect',
          'open',
          'watch:jade',
          'watch:stylus',
          'watch:copy',
          'watch:public'
        ],
        options: {
          logConcurrentOutput: true
        }
      }
    },
    useminPrepare: {
      html: 'public/index.html',
      options: {
        dest: 'public'
      }
    },
    usemin: {
      html: 'public/index.html'
    },
    'gh-pages': {
      public: {
        options: {
          base: 'public',
          message: 'Generated by generator-bespoketheme'
        },
        src: '**/*'
      }
    }
  };

  grunt.initConfig(config);

  // Load all Grunt tasks
  require('matchdep').filterDev('grunt-*').forEach(grunt.loadNpmTasks);

  grunt.registerTask('default', ['compile']);
  grunt.registerTask('compile', ['clean', 'concurrent:compile', 'copy']);
  grunt.registerTask('server', ['compile', 'concurrent:server']);
  grunt.registerTask('deploy', ['default', 'gh-pages:public']);

};
